import React, { useState, useEffect } from 'react';
import { Layout } from './components/Layout';
import { Header } from './components/Header';
import { HomeFeed } from './components/HomeFeed';
import { ExploreView } from './components/ExploreView';
import { StatusView } from './components/StatusView';
import { MarketplaceView } from './components/MarketplaceView';
import { CategoryView } from './components/CategoryView';
import { CategoriaAlimentacao } from './components/CategoriaAlimentacao';
import { SubcategoryStoreList } from './components/SubcategoryStoreList';
import { StoreDetailView } from './components/StoreDetailView';
import { StoreCategoryView } from './components/StoreCategoryView';
import { CashbackView } from './components/CashbackView';
import { CashbackLandingView } from './components/CashbackLandingView';
import { FreguesiaConnectPublic } from './components/FreguesiaConnectPublic';
import { FreguesiaConnectDashboard } from './components/FreguesiaConnectDashboard';
import { FreguesiaConnectRestricted } from './components/FreguesiaConnectRestricted';
import { RewardDetailsView } from './components/RewardDetailsView';
import { PrizeHistoryView } from './components/PrizeHistoryView';
import { AuthModal } from './components/AuthModal';
import { QuickRegister } from './components/QuickRegister';
import { MenuView } from './components/MenuView';
import { ServicesView } from './components/ServicesView';
import { SubcategoriesView } from './components/SubcategoriesView';
import { SpecialtiesView } from './components/SpecialtiesView';
import { StoreAreaView } from './components/StoreAreaView';
import { QuoteRequestModal } from './components/QuoteRequestModal';
import { ServiceSuccessView } from './components/ServiceSuccessView';
import { EditorialListView, EditorialCollection } from './components/EditorialListView';
import { SupportView, InviteFriendView, AboutView, FavoritesView, SponsorInfoView } from './components/SimplePages';
import { CashbackInfoView } from './components/CashbackInfoView';
import { EditProfileView } from './components/EditProfileView';
import { ServiceTermsView } from './components/ServiceTermsView';
import { PatrocinadorMasterScreen } from './components/PatrocinadorMasterScreen';
import { BusinessRegistrationFlow } from './components/BusinessRegistrationFlow';
import { StoreCashbackModule } from './components/StoreCashbackModule';
import { StoreAdsModule } from './components/StoreAdsModule';
import { StoreConnectModule } from './components/StoreConnectModule';
import { StoreProfileEdit } from './components/StoreProfileEdit';
import { StoreFinanceModule } from './components/StoreFinanceModule';
import { StoreSupportModule } from './components/StoreSupportModule';

/* ✅ CORREÇÃO AQUI */
import { MerchantQrScreen } from './src/components/MerchantQrScreen';

import { CashbackScanScreen } from './components/CashbackScanScreen';
import { CashbackPaymentScreen } from './components/CashbackPaymentScreen';
import { MerchantCashbackRequests } from './components/MerchantCashbackRequests';
import { MerchantPayRoute } from './components/MerchantPayRoute';
import { CashbackPayFromQrScreen } from './components/CashbackPayFromQrScreen';
import { MerchantPanel } from './components/MerchantPanel';
import { UserCashbackFlow } from './components/UserCashbackFlow';

import { MapPin, Crown } from 'lucide-react';
import { auth } from './lib/firebase';
import { onAuthStateChanged, User } from 'firebase/auth';
import { Category, Store, AdType } from './types';
import { getStoreLogo } from './utils/mockLogos';
